apiVersion: v1 
kind: Service
metadata: 
  name: loadlalancer-svc
  namespace: api-ns
spec:
  selector:
    app: app-api
  ports:
    - name: http-api
      targetPort: 8000
      port: 8000
      nodePort: 31100
  type: LoadBalancer