apiVersion: v1 
kind: Service
metadata: 
  name: {{ .Release.Name }}-lba
  namespace: {{ .Release.Name }}-ns
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - name: {{ .Release.Name }}-http
      targetPort: 8000
      port: 8000
  type: NodePort 